"use client";

import { createContext, useContext } from "react";
import type { AgentRuntimeId } from "@/lib/agent-runtime";

export type AppLanguage = "zh-CN" | "en-US";
export type AppTheme = "system" | "light" | "dark";
export type AgentModel = string;
export type AgentRuntime = AgentRuntimeId;
export type ThinkingLevel = "low" | "medium" | "high";

export interface AppSettings {
  language: AppLanguage;
  theme: AppTheme;
  defaultRuntime: AgentRuntime;
  defaultModel: AgentModel;
  defaultConnectionId: string | null;
  defaultThinkingLevel: ThinkingLevel;
  showActivityDetails: boolean;
  messageSounds: boolean;
  /** Whether documents open in the rich editor or as Markdown source. */
  documentEditor: "rich" | "source";
}

const en = {
  "nav.workspace": "Workspace navigation",
  "nav.home": "Home",
  "nav.documents": "Documents",
  "nav.tasks": "Tasks",
  "nav.agents": "Agents",
  "nav.channels": "Channels",
  "nav.machines": "Machines",
  "nav.createAgent": "Create agent",
  "nav.createChannel": "Create channel",
  "nav.settings": "Settings",
  "nav.resizeSidebar": "Resize sidebar",
  "sidebar.loadFailed": "Couldn't load the sidebar",
  "sidebar.loadTimedOut": "Loading the sidebar timed out. Teammate will retry automatically.",
  "workspace.create": "Create workspace",
  "createWorkspace.title": "Create workspace",
  "createWorkspace.description": "Set up a focused space for people and agents to collaborate.",
  "createWorkspace.name": "Workspace name",
  "createWorkspace.namePlaceholder": "e.g. Product, Research…",
  "createWorkspace.slug": "Workspace URL",
  "createWorkspace.slugPlaceholder": "product-team",
  "createWorkspace.slugHint": "Use lowercase letters, numbers, and single hyphens.",
  "createWorkspace.descriptionField": "Description",
  "createWorkspace.descriptionPlaceholder": "What will this workspace be used for?",
  "createWorkspace.optional": "optional",
  "createWorkspace.cancel": "Cancel",
  "createWorkspace.create": "Create",
  "createWorkspace.failed": "Could not create the workspace.",
  "createWorkspace.slugRequired": "Enter a workspace URL.",
  "createWorkspace.slugInvalid": "Use lowercase letters, numbers, and single hyphens only.",
  "createWorkspace.slugInUse": "That workspace URL is already in use.",
  "createWorkspace.invalidResponse": "The workspace was created, but its destination was missing.",
  "navigation.unsavedTitle": "Discard unsaved changes?",
  "navigation.unsavedDescription": "Your current edits have not been saved. You can stay and save them, or discard them and continue.",
  "navigation.busyTitle": "Save in progress",
  "navigation.busyDescription": "Please wait for the current save to finish before leaving this view.",
  "navigation.stay": "Stay",
  "navigation.discard": "Discard and continue",
  "workspace.agents": "Agents",
  "workspace.channels": "Channels",
  "workspace.members": "Members",
  "workspace.description": "Runs entirely on this computer with Node and SQLite.",
  "workspace.prompt": "Choose an agent or channel from the sidebar to start collaborating.",
  "workspace.loading": "Loading workspace…",
  "workspace.notFound": "Workspace not found",
  "workspace.notFoundDescription": "Check the workspace address, or return to your local workspace.",
  "workspace.loadFailed": "Could not load this workspace",
  "workspace.loadFailedDescription": "Teammate could not read this workspace. Check the local service and retry.",
  "workspace.openLocal": "Open local workspace",
  "workspace.countsFailed": "Workspace totals are temporarily unavailable",
  "workspaceMembers.description": "Review the people in this workspace and remove access when needed.",
  "workspaceMembers.loading": "Loading workspace members…",
  "workspaceMembers.loadFailed": "Couldn't load workspace members",
  "workspaceMembers.empty": "No human members were found in this workspace.",
  "workspaceMembers.you": "You",
  "workspaceMembers.role.owner": "Owner",
  "workspaceMembers.role.admin": "Admin",
  "workspaceMembers.role.member": "Member",
  "workspaceMembers.agentCount": "{count} owned agents",
  "workspaceMembers.remove": "Remove",
  "workspaceMembers.removeNamed": "Remove {name} from this workspace",
  "workspaceMembers.confirmTitle": "Remove this workspace member?",
  "workspaceMembers.confirmDescription": "Remove {name} and their {count} owned agents from this workspace? Their runtime keys will be revoked, direct conversations removed, channel access cleared, and assigned tasks unassigned. Existing shared channel messages are preserved. This does not affect their access or agents in other workspaces.",
  "workspaceMembers.cancel": "Cancel",
  "workspaceMembers.confirm": "Remove member",
  "workspaceMembers.removing": "Removing…",
  "workspaceMembers.removeFailed": "The member couldn't be removed. Try again.",
  "workspaceMembers.removed": "Removed {name} and {count} owned agents from this workspace.",
  "workspaceMembers.alreadyRemoved": "{name} was already removed. The member list is now up to date.",
  "documents.title": "Documents",
  "documents.description": "Generated and active artifacts isolated to this workspace.",
  "documents.emptyTitle": "No workspace documents yet",
  "documents.emptyDescription": "Documents generated or used in this workspace will appear here.",
  "documents.sidebarEmpty": "Documents you create will be listed here.",
  "documents.new": "New document",
  "documents.createFailed": "Couldn't create the document.",
  "documents.createTimedOut": "Document creation timed out. Refresh before trying again.",
  "documents.untitled": "Untitled document",
  "documents.saving": "Saving…",
  "documents.searchPlaceholder": "Search documents",
  "documents.columnTitle": "Title",
  "documents.columnOwner": "Author",
  "documents.columnUpdated": "Updated",
  "documents.columnCreated": "Created",
  "documents.columnLocation": "Location",
  "documents.groupPinned": "Pinned",
  "documents.pin": "Pin",
  "documents.unpin": "Unpin",
  "documents.newFolder": "New folder",
  "documents.rename": "Rename",
  "documents.newInFolder": "New document here",
  "documents.dropToUnfile": "Drop here to take out of a folder",
  "documents.locationRoot": "Workspace",
  "documents.newHint": "Start a blank document",
  "documents.importFolder": "Add a local folder",
  "documents.importFolderHint": "Pick one, or drop a folder here",
  "documents.importReading": "Reading {count} files…",
  "documents.imported": "Added {count} documents",
  "documents.importedSome": "Added {count}, the first {limit} in the folder",
  "documents.importNothing": "No readable notes in that folder",
  "documents.importFailed": "Could not read that folder",
  "documents.searchingFor": "Matching {query}",
  "documents.ownerYou": "You",
  "documents.groupToday": "Today",
  "documents.groupYesterday": "Yesterday",
  "documents.groupWeek": "Earlier this week",
  "documents.groupOlder": "Older",
  "documents.noMatches": "No documents match",
  "documents.noMatchesDescription": "Nothing here contains \u201c{query}\u201d.",
  "documents.editRich": "Rich text",
  "documents.editSource": "Markdown",
  "documents.editModeLocked": "This document keeps formatting the rich editor cannot rewrite safely, so it stays as Markdown source.",
  "documents.loading": "Loading documents…",
  "documents.saved": "Saved",
  "documents.generatedBy": "Generated by {name}",
  "documents.unsaved": "Unsaved changes",
  "documents.conflict": "A teammate edited this document, so their version was loaded.",
  "documents.save": "Save",
  "documents.saveFailed": "Couldn't save the document.",
  "documents.edit": "Edit",
  "documents.cancelEdit": "Cancel editing",
  "documents.delete": "Delete",
  "documents.deleteFailed": "Couldn't delete the document.",
  "documents.deleteTitle": "Delete this document?",
  "documents.deleteDescription": "This permanently removes the shared document from the workspace.",
  "documents.cancel": "Cancel",
  "documents.titleField": "Title",
  "documents.contentField": "Content",
  "documents.contentPlaceholder": "Write shared context, decisions, or reference notes…",
  "documents.noContent": "No content yet",
  "documents.open": "Open",
  "tasks.title": "Tasks",
  "tasks.description": "Work items created and handled by people and agents across channels.",
  "tasks.emptyTitle": "No tasks yet",
  "tasks.emptyDescription": "Tasks created from channel work will appear here with their owner and progress.",
  "tasks.loading": "Loading tasks…",
  "tasks.refresh": "Refresh tasks",
  "tasks.new": "New task",
  "tasks.newDescription": "Create a channel work item and optionally assign it or make it a subtask.",
  "tasks.titleField": "Task title",
  "tasks.titlePlaceholder": "What needs to be done?",
  "tasks.channelField": "Channel",
  "tasks.assigneeField": "Assignee",
  "tasks.statusField": "Status",
  "tasks.parentField": "Parent task",
  "tasks.noParent": "No parent task",
  "tasks.unassigned": "Unassigned",
  "tasks.create": "Create task",
  "tasks.creating": "Creating…",
  "tasks.cancel": "Cancel",
  "tasks.subtaskOf": "Subtask of #{number}",
  "tasks.count": "{count} tasks",
  "tasks.emptyColumn": "No tasks in this stage.",
  "tasks.dropHere": "Drop here to move",
  "tasks.dragHint": "Drag to move this task",
  "tasks.all": "All tasks",
  "tasks.open": "Open",
  "tasks.untitled": "Untitled task",
  "tasks.unknownChannel": "Unknown channel",
  "tasks.todo": "To do",
  "tasks.inProgress": "In progress",
  "tasks.inReview": "In review",
  "tasks.done": "Done",
  "runtime.starting": "Starting local workspace…",
  "runtime.error": "Teammate runtime failed to start",
  "runtime.errorDescription": "The local service did not become ready within 15 seconds. Make sure Teammate is running, then retry.",
  "runtime.conflictDescription": "Another Teammate process or local service is already using this app's port. Quit the older background process, then retry.",
  "runtime.retry": "Retry",
  "conversation.loading": "Loading conversation…",
  "conversation.loadFailed": "Couldn't load this conversation.",
  "conversation.notFound": "Conversation not found.",
  "conversation.realtimeDegraded": "Live updates were interrupted. Teammate is checking for replies in the background.",
  "conversation.agentDirectoryLoading": "Loading agent details…",
  "conversation.agentDirectoryUnavailable": "Agent details are unavailable. Regular channel messages can still be sent; agent mentions and direct messages are paused.",
  "conversation.select": "Select a conversation to start chatting",
  "message.loadingOlder": "Loading older messages…",
  "message.thread.oneReply": "1 reply",
  "message.thread.replyCount": "{count} replies",
  "message.thread.lastReply": "Last reply {time}",
  "message.thread.view": "View thread",
  "message.thread.replyInThread": "Reply in thread",
  "message.reaction.add": "Add reaction",
  "message.documentSuggestions": "Documents",
  "emoji.search": "Search emoji",
  "emoji.recent": "Frequently used",
  "emoji.results": "Search results",
  "emoji.empty": "No emoji found",
  "emoji.group.smileys": "Smileys & emotion",
  "emoji.group.people": "People & body",
  "emoji.group.nature": "Animals & nature",
  "emoji.group.food": "Food & drink",
  "emoji.group.travel": "Travel & places",
  "emoji.group.activities": "Activities",
  "emoji.group.objects": "Objects",
  "emoji.group.symbols": "Symbols",
  "emoji.group.flags": "Flags",
  "message.thread.title": "Thread",
  "message.dropFiles": "Drop to attach",
  "message.newMessagesLine": "New",
  "message.jumpToUnread": "Jump",
  "message.edit": "Edit message",
  "message.editSave": "Save",
  "message.editCancel": "Cancel",
  "message.edited": "(edited)",
  "message.editFailed": "Couldn't save the edit.",
  "message.delete": "Delete message",
  "message.deleteConfirm": "Delete this message? This cannot be undone.",
  "message.deleteFailed": "Couldn't delete the message.",
  "message.thread.alsoSend": "Also send to {channel}",
  "message.thread.broadcastFrom": "Replied to a thread: {excerpt}",
  "message.thread.placeholder": "Reply…",
  "message.thread.close": "Close thread",
  "message.thread.empty": "No replies yet. Start the thread.",
  "message.thread.loadFailed": "Couldn't load this thread.",
  "message.loadOlderFailed": "Couldn't load older messages.",
  "message.retryOlder": "Try again",
  "message.beginning": "Beginning of conversation",
  "message.system": "System",
  "message.agent": "Agent",
  "agent.departed": "Left",
  "agent.departConfirm": "Remove {name} from the workspace? Their messages, documents and task history stay, marked as having left.",
  "agent.depart": "Remove from workspace",
  "message.you": "You",
  "message.agentBadge": "agent",
  "message.thinking": "Thinking",
  "message.working": "Working",
  "message.runtimeError": "Runtime error",
  "message.newMessage": "1 new message",
  "message.newMessages": "{count} new messages",
  "message.agentReplyAnnouncement": "An agent sent a new reply.",
  "message.agentRepliesAnnouncement": "Agents sent {count} new replies.",
  "message.responseFailedTitle": "Agent response stopped",
  "message.responseFailedDescription": "The agent runtime reported an error before a reply arrived. Check the runtime or agent status, then try again.",
  "message.runtimeErrorUnsupportedModel": "This model is not available for the selected runtime or connection. Open agent settings, choose Automatic (recommended) for Codex or a model offered by the connection, then retry.",
  "message.runtimeErrorAuthentication": "The model connection needs to be authenticated again. Reconnect it in Settings, then retry.",
  "message.runtimeErrorRateLimit": "The model service is busy or has reached its usage limit. Wait a moment, then retry.",
  "message.runtimeErrorNetwork": "Teammate could not reach the model service. Check the connection and retry.",
  "message.runtimeErrorUnknown": "The agent runtime stopped unexpectedly. Check its model and connection settings, then retry.",
  "message.responseDelayedTitle": "Still waiting for a reply",
  "message.responseDelayedDescription": "No reply arrived. Check the runtime or agent status, then retry.",
  "message.dismiss": "Dismiss",
  "message.send": "Send",
  "message.today": "Today",
  "message.yesterday": "Yesterday",
  "message.attachFile": "Attach a file",
  "message.showFormatting": "Show formatting",
  "message.mentionSomeone": "Mention someone",
  "message.newLineHint": "to add a new line",
  "message.format.bold": "Bold",
  "message.format.italic": "Italic",
  "message.format.strike": "Strikethrough",
  "message.format.orderedList": "Ordered list",
  "message.format.bulletList": "Bulleted list",
  "message.format.blockquote": "Blockquote",
  "message.format.code": "Code",
  "message.format.codeBlock": "Code block",
  "message.sending": "Sending…",
  "message.sendFailed": "Message wasn't sent.",
  "message.sendTimedOut": "Delivery timed out.",
  "message.sendFailedInline": "Message wasn't sent. It is kept above so you can retry.",
  "message.deliveryPending": "Sending…",
  "message.deliverySent": "Sent",
  "message.deliveryFailed": "Not sent",
  "message.retryDelivery": "Retry",
  "message.agentOffline": "This agent is offline. Messages will remain queued until its runtime is available.",
  "message.agentLoading": "The conversation is still loading. Try again in a moment.",
  "message.agentUnavailable": "This direct conversation has no available agent.",
  "message.mentionedAgentsOffline": "{names} is offline. The message is queued, and Teammate will try to deliver it when the runtime is available.",
  "message.agentPlaceholder": "Message {name}",
  "message.channelPlaceholder": "Message #{name}",
  "message.mentionSuggestions": "Agent suggestions",
  "message.agentSettings": "Agent settings",
  "agentSettings.settings": "Settings",
  "agentSettings.workspace": "Workspace",
  "agentSettings.close": "Close",
  "agentSettings.loading": "Loading…",
  "agentSettings.verifyingAccess": "Checking access…",
  "agentSettings.accessFailed": "Couldn't open agent settings",
  "agentSettings.accessFailedDescription": "Teammate couldn't verify that you can manage this agent. Check your connection and try again.",
  "agentSettings.basicInfo": "Basic info",
  "agentSettings.avatar": "Avatar",
  "agentSettings.customImage": "Custom image",
  "agentSettings.chooseAvatar": "Choose an avatar",
  "agentSettings.avatarUploadHint": "PNG, JPEG or WebP, up to 2 MB",
  "agentSettings.avatarGeneratedHint": "Choose a generated avatar",
  "agentSettings.upload": "Upload",
  "agentSettings.defaultAvatar": "Default avatar",
  "agentSettings.useDefaultAvatar": "Use default avatar",
  "agentSettings.generatedAvatar": "Generated avatar",
  "agentSettings.chooseGeneratedAvatar": "Choose generated avatar",
  "agentSettings.displayName": "Display name",
  "agentSettings.description": "Description",
  "agentSettings.descriptionPlaceholder": "What does this agent do?",
  "agentSettings.runtime": "Runtime",
  "agentSettings.model": "Model",
  "agentSettings.selectModel": "Select model",
  "agentSettings.connection": "Connection",
  "agentSettings.chooseConnection": "Choose…",
  "agentSettings.loadingConnections": "Loading model connections…",
  "agentSettings.instructions": "Instructions",
  "agentSettings.systemPrompt": "System prompt",
  "agentSettings.systemPromptPlaceholder": "Who this teammate is and what they are responsible for…",
  "agentSettings.systemPromptHelp": "This opens the brief the agent is given. Teammate adds the rest — how to send messages, use threads, claim tasks, write documents, keep memory, and when to speak or stay quiet. Write who this teammate is and what they own; you do not need to repeat any of that, and instructions that contradict it tend to lose.",
  "agentSettings.promptPreview": "See the full brief this agent receives",
  "agentSettings.promptPreviewLoading": "Building…",
  "agentSettings.promptPreviewMemory": "(your MEMORY.md is inserted here at run time)",
  "agentSettings.saved": "Saved!",
  "agentSettings.saveChanges": "Save changes",
  "agentSettings.skills": "Skills",
  "agentSettings.installedSkills": "{count} installed",
  "agentSettings.loadingSkills": "Loading skills…",
  "agentSettings.noSkills": "No skills installed",
  "agentSettings.skillsSourcePrefix": "Skills are loaded from",
  "agentSettings.skillsSourceSuffix": "and shared across all agents.",
  "agentSettings.dangerZone": "Danger zone",
  "agentSettings.resetConversation": "Reset conversation",
  "agentSettings.deleteAgent": "Remove from workspace",
  "agentSettings.resetTitle": "Reset conversation?",
  "agentSettings.deleteTitle": "Remove this teammate?",
  "agentSettings.resetDescription": "This permanently removes every message in the direct conversation with this agent.",
  "agentSettings.deleteDescription": "They stop receiving messages and leave every channel. What they wrote — messages, documents, task history — stays where it is, marked as having left.",
  "agentSettings.cancel": "Cancel",
  "agentSettings.workspaceLoading": "Loading workspace…",
  "agentSettings.runtimeOffline": "Agent runtime is offline",
  "agentSettings.runtimeOfflineDescription": "The workspace files are on the machine running this agent. Start its runtime to browse them here.",
  "agentSettings.retry": "Retry",
  "agentSettings.copyPath": "Copy path",
  "agentSettings.refresh": "Refresh",
  "agentSettings.copied": "Copied!",
  "agentSettings.empty": "Empty",
  "agentSettings.workspaceEmpty": "Workspace is empty",
  "agentSettings.workspaceEmptyDescription": "The agent will create files here as it learns from conversations.",
  "agentSettings.previewMarkdown": "Preview Markdown",
  "agentSettings.closePreview": "Close preview",
  "agentSettings.workspaceInfoPrefix": "This is the agent's persistent workspace. It stores",
  "agentSettings.workspaceInfoSuffix": "and notes that help the agent maintain context across conversations.",
  "agentSettings.error.unknown": "Unknown error",
  "agentSettings.error.agentMissing": "Agent settings were not found.",
  "agentSettings.error.loadAgent": "Could not load agent settings: {message}",
  "agentSettings.error.skillsInvalid": "The skills service returned an invalid response.",
  "agentSettings.error.requestStatus": "Request failed ({status})",
  "agentSettings.error.loadSkills": "Could not load skills: {message}",
  "agentSettings.error.skillsOffline": "Could not load skills because the agent runtime is offline.",
  "agentSettings.error.loadConnections": "Could not load local runtimes and model connections.",
  "agentSettings.error.avatarType": "Choose a PNG, JPEG, or WebP image.",
  "agentSettings.error.avatarSize": "Avatar must be 2 MB or smaller.",
  "agentSettings.error.avatarRead": "Could not read that image.",
  "agentSettings.error.save": "Could not save changes: {message}",
  "agentSettings.error.reset": "Could not reset the conversation: {message}",
  "agentSettings.error.delete": "Could not delete the agent: {message}",
  "agentSettings.error.loadWorkspace": "Could not load the workspace: {message}",
  "agentSettings.error.fileInvalid": "The file service returned an invalid response.",
  "agentSettings.error.readFile": "Could not read the file: {message}",
  "agentSettings.error.readFileOffline": "Could not read the file because the agent runtime is offline.",
  "settings.title": "Settings",
  "settings.description": "Customize Teammate on this computer.",
  "settings.loading": "Loading settings…",
  "settings.loadFailed": "Couldn't load settings.",
  "settings.requestTimedOut": "The request timed out. Try again.",
  "settings.profileLoading": "Loading your profile…",
  "settings.profileLoadFailed": "Couldn't load your profile.",
  "settings.navGeneral": "General",
  "settings.navProfile": "My profile",
  "settings.navWorkspace": "Workspace members",
  "settings.navModels": "AI",
  "settings.engineHeading": "Engine",
  "settings.engineInUse": "in use",
  "settings.engineVia": "Through",
  "settings.engineNeedsConnection": "Add a model connection below to use this",
  "settings.engineReady": "Ready",
  "settings.engineUnconfigured": "Needs a connection",
  "settings.navChat": "Chat",
  "settings.navAdvanced": "Advanced",
  "settings.interface": "Interface",
  "settings.profileDescription": "Choose how you appear in conversations on this computer.",
  "settings.profileAvatar": "Avatar",
  "settings.profileName": "Display name",
  "settings.profileNameRequired": "Display name cannot be empty.",
  "settings.profileSaveAfterSettingsError": "App settings were saved, but your profile was not.",
  "settings.profileUpload": "Upload image",
  "settings.profileAvatarHint": "PNG, JPEG or WebP, up to 2 MB.",
  "settings.generalDescription": "Language and appearance for this app.",
  "settings.language": "Language",
  "settings.languageZh": "简体中文",
  "settings.languageEn": "English",
  "settings.appearance": "Appearance",
  "settings.themeSystem": "Follow system",
  "settings.themeLight": "Light",
  "settings.themeDark": "Dark",
  "settings.agentRuntime": "Agent runtime",
  "settings.runtimeDescription": "Choose the local engine used by new agents and check CLI availability.",
  "settings.availableRuntimes": "Available runtimes",
  "settings.runtime": "Default runtime",
  "settings.runtimeClaude": "Claude Code",
  "settings.runtimeCodex": "Codex",
  "settings.runtimePi": "Pi / Custom API",
  "settings.defaultModel": "Default model",
  "settings.thinkingLevel": "Thinking depth",
  "settings.thinkingLow": "Low",
  "settings.thinkingMedium": "Medium",
  "settings.thinkingHigh": "High",
  "settings.thinkingXHigh": "Extra high",
  "settings.thinkingHint": "Used as the reasoning effort for new agents. Models without reasoning support ignore it.",
  "settings.defaultSettings": "Default settings",
  "settings.workspaceOverride": "Workspace settings",
  "settings.workspaceInherited": "Inherits the default model and thinking depth",
  "settings.capabilities": "Model capabilities",
  "settings.contextWindow": "Context window",
  "settings.reasoningCapability": "Reasoning",
  "settings.imageCapability": "Image input",
  "settings.available": "Available",
  "settings.modelsDescription": "Choose how Teammate thinks and manage the model connections it can use.",
  "settings.modelOpus": "Opus — Most capable",
  "settings.modelSonnet": "Sonnet — Balanced",
  "settings.modelHaiku": "Haiku — Fastest",
  "settings.modelCodexDefault": "Use Codex default",
  "settings.runtimeInstalled": "Installed",
  "settings.runtimeMissing": "CLI not found",
  "settings.codexModelPlaceholder": "default or a Codex model ID",
  "settings.modelHint": "Used when creating new agents. Existing agents keep their own model setting.",
  "settings.runtimeHint": "Claude Code and Codex use their installed CLI and existing local login.",
  "settings.connections": "Model connections",
  "settings.connectionsHint": "Keys and OAuth tokens are encrypted on this computer and never stored in SQLite.",
  "settings.chatGptOAuth": "ChatGPT Plus / Pro",
  "settings.chatGptOAuthHint": "Use your Codex subscription through a secure browser sign-in.",
  "settings.claudeOAuth": "Claude Pro / Max",
  "settings.claudeOAuthHint": "Use your Claude subscription through a secure browser sign-in.",
  "settings.copilotOAuth": "GitHub Copilot",
  "settings.copilotOAuthHint": "Use your Copilot subscription. GitHub will ask for the code below.",
  "settings.deviceCodeHint": "Enter this code on the page that just opened:",
  "settings.connect": "Connect",
  "settings.connecting": "Waiting for sign-in…",
  "settings.connected": "Connected",
  "settings.addApi": "Add custom API",
  "settings.connectionName": "Connection name",
  "settings.provider": "API protocol",
  "settings.baseUrl": "Base URL",
  "settings.apiKey": "API key",
  "settings.connectionModel": "Model ID",
  "settings.addConnection": "Save connection",
  "settings.addConnectionTitle": "Add connection",
  "settings.addConnectionDescription": "Connect ChatGPT or add a compatible API. Models stay scoped to this connection.",
  "settings.noConnections": "No model connections yet.",
  "settings.defaultBadge": "Default",
  "settings.setDefault": "Use as default",
  "settings.connectionActions": "Connection actions",
  "settings.localManagedConnection": "Managed by the installed local CLI",
  "settings.connectionSaveFailed": "Could not save the model connection",
  "settings.connectionRefreshFailed": "The connection was updated, but the list could not be refreshed. Reopen settings to retry.",
  "settings.configurationCheck": "Check configuration",
  "settings.configurationChecking": "Checking…",
  "settings.configurationValid": "Configuration is valid",
  "settings.configurationInvalid": "Configuration needs attention",
  "settings.refreshModels": "Refresh models",
  "settings.refreshingModels": "Refreshing…",
  "settings.modelsCount": "{count} available models",
  "settings.modelCatalogEmpty": "No available models",
  "settings.oauthFailed": "Could not complete ChatGPT sign-in",
  "settings.removeConnection": "Remove",
  "settings.removeConnectionTitle": "Remove model connection?",
  "settings.removeConnectionDescription": "This removes the encrypted credential for",
  "settings.removeConnectionFailed": "Could not remove the model connection",
  "settings.removeConnectionRecoverable": "The credential was removed, but the connection record was retained. Reconnect it or retry removal.",
  "settings.removeDefaultConnectionBlocked": "Choose another default connection before removing this one.",
  "settings.removeUsedConnectionBlocked": "Reassign the {count} agents using this connection before removing it.",
  "settings.chooseConnection": "Model connection",
  "settings.chat": "Chat",
  "settings.chatDescription": "Control how agent progress and failures appear in conversations.",
  "settings.showActivityDetails": "Show activity details",
  "settings.showActivityDetailsHint": "Show safe, user-facing activity context beside the agent's status when available.",
  "settings.messageSounds": "Message sounds",
  "settings.messageSoundsHint": "Play a subtle local cue when a message is sent or received.",
  "settings.runtimeErrors": "Runtime failures",
  "settings.runtimeErrorsHint": "Failures are saved as visible messages in the conversation so they are never silently lost.",
  "settings.advanced": "Advanced",
  "settings.advancedDescription": "Local service and runtime diagnostics for troubleshooting.",
  "settings.localService": "Local service",
  "settings.executablePath": "Executable path",
  "settings.embeddedRuntime": "Embedded runtime",
  "settings.cancel": "Cancel",
  "settings.save": "Save settings",
  "settings.saving": "Saving…",
  "createAgent.title": "Create Agent",
  "createAgent.description": "Add a new AI agent to your workspace.",
  "createAgent.name": "Name",
  "createAgent.namePlaceholder": "e.g. Design Assistant, Code Reviewer…",
  "createAgent.descriptionField": "Description",
  "createAgent.descriptionPlaceholder": "What does this agent do?",
  "createAgent.runtime": "Runtime",
  "createAgent.model": "Model",
  "createAgent.instructions": "Instructions",
  "createAgent.instructionsPlaceholder": "Tell the agent how to behave, what it is good at, and what tools to use…",
  "createAgent.optional": "optional",
  "createAgent.cancel": "Cancel",
  "createAgent.submit": "Create Agent",
  "createChannel.title": "Create Channel",
  "createChannel.description": "Create a new group channel for your workspace.",
  "createChannel.name": "Channel name",
  "createChannel.namePlaceholder": "e.g. design, marketing, dev…",
  "createChannel.descriptionField": "Description",
  "createChannel.descriptionPlaceholder": "What is this channel about?",
  "createChannel.invite": "Invite agents",
  "createChannel.optional": "optional",
  "createChannel.cancel": "Cancel",
  "createChannel.submit": "Create Channel",
  "channel.manageAgents": "Manage channel agents",
  "channel.editTitle": "Channel settings",
  "channel.editDescription": "Update channel details and choose which agents can participate.",
  "channel.agents": "Agents in channel",
  "channel.save": "Save changes",
  "channel.notAuthenticated": "Sign in again to manage channels.",
  "channel.notWorkspaceMember": "You are no longer a member of this workspace.",
  "channel.loadingAgents": "Loading eligible agents…",
  "channel.searchAgents": "Search agents",
  "channel.noMatchingAgents": "No agents match this search.",
  "channel.loadAgentsFailed": "Couldn't load eligible agents.",
  "channel.loadTimedOut": "Loading agents timed out. Try again.",
  "channel.createTimedOut": "Channel creation timed out. Refresh before trying again.",
  "channel.updateTimedOut": "Saving the channel timed out. Refresh before trying again.",
  "channel.retry": "Retry",
  "channel.noEligibleAgents": "No workspace agents are available to invite.",
  "channel.agentEligibilityChanged": "Agent availability changed. Review the updated selection and try again.",
  "channel.createFailed": "Couldn't create the channel.",
  "channel.nameInUse": "A channel with this name already exists in this workspace.",
  "channel.inviteFailed": "Couldn't invite the selected agents.",
  "channel.createPartialFailure": "The channel was created, but its membership could not be verified. It is now visible in the sidebar; open its settings before retrying.",
  "channel.membershipChangedElsewhere": "Channel membership changed elsewhere. Your selection is preserved; review it before saving.",
  "channel.membershipSyncFailed": "Channel membership could not be synchronized.",
  "channel.notFound": "This channel is no longer available in the workspace.",
  "channel.updateNotApplied": "The channel update could not be verified.",
  "channel.updateFailed": "Couldn't update the channel.",
  "channel.delete": "Delete channel",
  "channel.deleteTitle": "Delete this channel?",
  "channel.deleteDescription": "This permanently removes #{name}, its tasks, and its conversation history.",
  "channel.deleteFailed": "Couldn't delete the channel.",
  "channel.deleteTimedOut": "Channel deletion timed out. Refresh before trying again.",
  "channel.partialFailure": "Some changes may have been saved; the latest membership has been reloaded.",
  "channel.rollbackSucceeded": "No membership changes were saved.",
} as const;

export type TranslationKey = keyof typeof en;

const zh: Record<TranslationKey, string> = {
  "nav.workspace": "工作区导航",
  "nav.home": "主页",
  "nav.documents": "文档",
  "nav.tasks": "任务",
  "nav.agents": "智能体",
  "nav.channels": "频道",
  "nav.machines": "设备",
  "nav.createAgent": "新建智能体",
  "nav.createChannel": "新建频道",
  "nav.settings": "设置",
  "nav.resizeSidebar": "调整侧边栏宽度",
  "sidebar.loadFailed": "侧边栏加载失败",
  "sidebar.loadTimedOut": "侧边栏加载超时，Teammate 会自动重试。",
  "workspace.create": "新建工作区",
  "createWorkspace.title": "新建工作区",
  "createWorkspace.description": "为人与智能体创建一个专注协作的空间。",
  "createWorkspace.name": "工作区名称",
  "createWorkspace.namePlaceholder": "例如：产品、研究…",
  "createWorkspace.slug": "工作区地址",
  "createWorkspace.slugPlaceholder": "product-team",
  "createWorkspace.slugHint": "使用小写字母、数字和单个连字符。",
  "createWorkspace.descriptionField": "描述",
  "createWorkspace.descriptionPlaceholder": "这个工作区准备做什么？",
  "createWorkspace.optional": "可选",
  "createWorkspace.cancel": "取消",
  "createWorkspace.create": "创建",
  "createWorkspace.failed": "无法创建工作区。",
  "createWorkspace.slugRequired": "请输入工作区地址。",
  "createWorkspace.slugInvalid": "仅可使用小写字母、数字和单个连字符。",
  "createWorkspace.slugInUse": "这个工作区地址已经被使用。",
  "createWorkspace.invalidResponse": "工作区已创建，但没有返回可用地址。",
  "navigation.unsavedTitle": "放弃未保存的更改？",
  "navigation.unsavedDescription": "当前编辑尚未保存。你可以留在这里保存，或放弃更改后继续。",
  "navigation.busyTitle": "正在保存",
  "navigation.busyDescription": "请等待当前保存完成后再离开此页面。",
  "navigation.stay": "留在这里",
  "navigation.discard": "放弃并继续",
  "workspace.agents": "智能体",
  "workspace.channels": "频道",
  "workspace.members": "成员",
  "workspace.description": "完全运行在本机，使用 Node 和 SQLite。",
  "workspace.prompt": "从左侧选择一个智能体或频道开始协作。",
  "workspace.loading": "正在加载工作区…",
  "workspace.notFound": "未找到工作区",
  "workspace.notFoundDescription": "请检查工作区地址，或返回本地工作区。",
  "workspace.loadFailed": "无法加载这个工作区",
  "workspace.loadFailedDescription": "Teammate 无法读取这个工作区，请检查本地服务后重试。",
  "workspace.openLocal": "打开本地工作区",
  "workspace.countsFailed": "工作区统计暂时不可用",
  "workspaceMembers.description": "查看当前工作区中的人员，并在需要时移除访问权限。",
  "workspaceMembers.loading": "正在加载工作区成员…",
  "workspaceMembers.loadFailed": "无法加载工作区成员",
  "workspaceMembers.empty": "当前工作区没有可显示的人员成员。",
  "workspaceMembers.you": "你",
  "workspaceMembers.role.owner": "所有者",
  "workspaceMembers.role.admin": "管理员",
  "workspaceMembers.role.member": "成员",
  "workspaceMembers.agentCount": "拥有 {count} 个智能体",
  "workspaceMembers.remove": "移除",
  "workspaceMembers.removeNamed": "将 {name} 移出当前工作区",
  "workspaceMembers.confirmTitle": "移除这位工作区成员？",
  "workspaceMembers.confirmDescription": "确定将 {name} 及其拥有的 {count} 个智能体移出当前工作区吗？相关运行时密钥会被撤销，私聊会被删除，频道权限会被清除，已分配任务会变为未分配。共享频道中的既有消息会保留，也不会影响此人在其他工作区中的权限和智能体。",
  "workspaceMembers.cancel": "取消",
  "workspaceMembers.confirm": "移除成员",
  "workspaceMembers.removing": "正在移除…",
  "workspaceMembers.removeFailed": "无法移除该成员，请重试。",
  "workspaceMembers.removed": "已将 {name} 及其拥有的 {count} 个智能体移出当前工作区。",
  "workspaceMembers.alreadyRemoved": "{name} 已经不在当前工作区，成员列表已刷新。",
  "documents.title": "文档",
  "documents.description": "展示当前工作区中生成和正在使用的产物，内容与其他工作区隔离。",
  "documents.emptyTitle": "还没有工作区文档",
  "documents.emptyDescription": "由当前工作区生成或正在使用的文档会显示在这里。",
  "documents.sidebarEmpty": "创建后的文档会显示在这里。",
  "documents.new": "新建文档",
  "documents.createFailed": "文档创建失败。",
  "documents.createTimedOut": "创建文档超时，请刷新后再重试。",
  "documents.untitled": "未命名文档",
  "documents.saving": "保存中…",
  "documents.searchPlaceholder": "搜索文档",
  "documents.columnTitle": "标题",
  "documents.columnOwner": "作者",
  "documents.columnUpdated": "最近更新",
  "documents.columnCreated": "创建时间",
  "documents.columnLocation": "位置",
  "documents.groupPinned": "置顶",
  "documents.pin": "置顶",
  "documents.unpin": "取消置顶",
  "documents.newFolder": "新建文件夹",
  "documents.rename": "重命名",
  "documents.newInFolder": "在此新建文档",
  "documents.dropToUnfile": "拖到这里可移出文件夹",
  "documents.locationRoot": "工作区",
  "documents.newHint": "从空白文档开始",
  "documents.importFolder": "添加本地文件夹",
  "documents.importFolderHint": "选一个，或把文件夹拖到这里",
  "documents.importReading": "正在读取 {count} 个文件…",
  "documents.imported": "已添加 {count} 篇文档",
  "documents.importedSome": "已添加 {count} 篇，取该文件夹中的前 {limit} 个",
  "documents.importNothing": "该文件夹里没有可读取的笔记",
  "documents.importFailed": "无法读取该文件夹",
  "documents.searchingFor": "匹配 {query}",
  "documents.ownerYou": "你",
  "documents.groupToday": "今天",
  "documents.groupYesterday": "昨天",
  "documents.groupWeek": "本周内",
  "documents.groupOlder": "更早",
  "documents.noMatches": "没有匹配的文档",
  "documents.noMatchesDescription": "这里没有包含「{query}」的内容。",
  "documents.editRich": "富文本",
  "documents.editSource": "Markdown",
  "documents.editModeLocked": "这篇文档含有富文本编辑器无法安全还原的格式，因此固定按 Markdown 源码编辑。",
  "documents.loading": "正在加载文档…",
  "documents.saved": "已保存",
  "documents.generatedBy": "由 {name} 生成",
  "documents.unsaved": "有未保存的更改",
  "documents.conflict": "有同事改了这篇文档，已载入他们的版本。",
  "documents.save": "保存",
  "documents.saveFailed": "文档保存失败。",
  "documents.edit": "编辑",
  "documents.cancelEdit": "取消编辑",
  "documents.delete": "删除",
  "documents.deleteFailed": "文档删除失败。",
  "documents.deleteTitle": "删除这份文档？",
  "documents.deleteDescription": "这会从工作区中永久删除这份共享文档。",
  "documents.cancel": "取消",
  "documents.titleField": "标题",
  "documents.contentField": "内容",
  "documents.contentPlaceholder": "记录共享上下文、决策或参考资料…",
  "documents.noContent": "还没有内容",
  "documents.open": "打开",
  "tasks.title": "任务",
  "tasks.description": "汇总各频道中由人与智能体创建和推进的工作项。",
  "tasks.emptyTitle": "还没有任务",
  "tasks.emptyDescription": "从频道工作中创建的任务会显示在这里，并带有负责人和进度。",
  "tasks.loading": "正在加载任务…",
  "tasks.refresh": "刷新任务",
  "tasks.new": "新建任务",
  "tasks.newDescription": "创建一个频道工作项，也可以直接分配负责人或设为子任务。",
  "tasks.titleField": "任务标题",
  "tasks.titlePlaceholder": "需要完成什么？",
  "tasks.channelField": "频道",
  "tasks.assigneeField": "负责人",
  "tasks.statusField": "状态",
  "tasks.parentField": "父任务",
  "tasks.noParent": "无父任务",
  "tasks.unassigned": "未分配",
  "tasks.create": "创建任务",
  "tasks.creating": "正在创建…",
  "tasks.cancel": "取消",
  "tasks.subtaskOf": "属于任务 #{number}",
  "tasks.count": "{count} 个任务",
  "tasks.emptyColumn": "此阶段暂无任务。",
  "tasks.dropHere": "拖放到这里移动任务",
  "tasks.dragHint": "拖动以移动此任务",
  "tasks.all": "全部任务",
  "tasks.open": "打开",
  "tasks.untitled": "未命名任务",
  "tasks.unknownChannel": "未知频道",
  "tasks.todo": "待处理",
  "tasks.inProgress": "进行中",
  "tasks.inReview": "待审核",
  "tasks.done": "已完成",
  "runtime.starting": "正在启动本地工作区…",
  "runtime.error": "Teammate 本地运行时启动失败",
  "runtime.errorDescription": "本地服务未在 15 秒内就绪，请确认 Teammate 正在运行后重试。",
  "runtime.conflictDescription": "另一个 Teammate 后台进程或本地服务正在占用应用端口。请先退出旧进程，然后重试。",
  "runtime.retry": "重试",
  "conversation.loading": "正在加载会话…",
  "conversation.loadFailed": "无法加载这个会话。",
  "conversation.notFound": "未找到这个会话。",
  "conversation.realtimeDegraded": "实时连接已中断，Teammate 正在后台检查新回复。",
  "conversation.agentDirectoryLoading": "正在加载智能体信息…",
  "conversation.agentDirectoryUnavailable": "智能体信息暂时不可用。普通频道消息仍可发送；@ 提及智能体和私聊暂时停用。",
  "conversation.select": "选择一个会话开始聊天",
  "message.loadingOlder": "正在加载更早的消息…",
  "message.thread.oneReply": "1 条回复",
  "message.thread.replyCount": "{count} 条回复",
  "message.thread.lastReply": "最后回复于 {time}",
  "message.thread.view": "查看话题",
  "message.thread.replyInThread": "在话题中回复",
  "message.reaction.add": "添加回应",
  "message.documentSuggestions": "文档",
  "emoji.search": "搜索表情",
  "emoji.recent": "最近使用",
  "emoji.results": "搜索结果",
  "emoji.empty": "没有找到表情",
  "emoji.group.smileys": "表情与情感",
  "emoji.group.people": "人物与肢体",
  "emoji.group.nature": "动物与自然",
  "emoji.group.food": "食物与饮品",
  "emoji.group.travel": "旅行与地点",
  "emoji.group.activities": "活动",
  "emoji.group.objects": "物品",
  "emoji.group.symbols": "符号",
  "emoji.group.flags": "旗帜",
  "message.thread.title": "话题",
  "message.dropFiles": "松手即可添加附件",
  "message.newMessagesLine": "新消息",
  "message.jumpToUnread": "跳转",
  "message.edit": "编辑消息",
  "message.editSave": "保存",
  "message.editCancel": "取消",
  "message.edited": "（已编辑）",
  "message.editFailed": "编辑没能保存。",
  "message.delete": "删除消息",
  "message.deleteConfirm": "删除这条消息？此操作无法撤销。",
  "message.deleteFailed": "删除失败。",
  "message.thread.alsoSend": "同时发送到 {channel}",
  "message.thread.broadcastFrom": "回复了话题：{excerpt}",
  "message.thread.placeholder": "回复…",
  "message.thread.close": "关闭话题",
  "message.thread.empty": "还没有回复，来开个头吧。",
  "message.thread.loadFailed": "无法加载这个话题。",
  "message.loadOlderFailed": "更早的消息加载失败。",
  "message.retryOlder": "重试",
  "message.beginning": "会话开始",
  "message.system": "系统",
  "message.agent": "智能体",
  "agent.departed": "已离职",
  "agent.departConfirm": "把 {name} 移出工作区？TA 说过的话、写过的文档和任务记录都会保留，并标记为已离职。",
  "agent.depart": "移出工作区",
  "message.you": "你",
  "message.agentBadge": "智能体",
  "message.thinking": "思考中",
  "message.working": "工作中",
  "message.runtimeError": "运行时错误",
  "message.newMessage": "1 条新消息",
  "message.newMessages": "{count} 条新消息",
  "message.agentReplyAnnouncement": "智能体发来了一条新回复。",
  "message.agentRepliesAnnouncement": "智能体发来了 {count} 条新回复。",
  "message.responseFailedTitle": "智能体回复已停止",
  "message.responseFailedDescription": "智能体运行时在回复前报告了错误。请检查运行时或智能体状态后重试。",
  "message.runtimeErrorUnsupportedModel": "当前运行时或连接不支持这个模型。请打开智能体设置：Codex 选择“自动（推荐）”，其他连接选择其提供的模型，然后重试。",
  "message.runtimeErrorAuthentication": "模型连接需要重新授权。请在设置中重新连接后再试。",
  "message.runtimeErrorRateLimit": "模型服务正忙或已达到用量限制，请稍后重试。",
  "message.runtimeErrorNetwork": "Teammate 暂时无法连接模型服务，请检查网络或连接设置后重试。",
  "message.runtimeErrorUnknown": "智能体运行时意外停止。请检查模型和连接设置后重试。",
  "message.responseDelayedTitle": "仍未收到回复",
  "message.responseDelayedDescription": "暂时没有收到回复。请检查运行时或智能体状态后重试。",
  "message.dismiss": "关闭",
  "message.send": "发送",
  "message.today": "今天",
  "message.yesterday": "昨天",
  "message.attachFile": "添加文件",
  "message.showFormatting": "显示格式",
  "message.mentionSomeone": "提及某个成员",
  "message.newLineHint": "可添加新行",
  "message.format.bold": "粗体",
  "message.format.italic": "斜体",
  "message.format.strike": "删除线",
  "message.format.orderedList": "有序列表",
  "message.format.bulletList": "项目符号列表",
  "message.format.blockquote": "块引用",
  "message.format.code": "行内代码",
  "message.format.codeBlock": "代码块",
  "message.sending": "发送中…",
  "message.sendFailed": "消息未发送。",
  "message.sendTimedOut": "发送超时。",
  "message.sendFailedInline": "消息未发送，内容已保留在上方，可直接重试。",
  "message.deliveryPending": "发送中…",
  "message.deliverySent": "已发送",
  "message.deliveryFailed": "未发送",
  "message.retryDelivery": "重试",
  "message.agentOffline": "智能体当前离线，消息会排队等待运行时恢复。",
  "message.agentLoading": "会话仍在加载，请稍后再试。",
  "message.agentUnavailable": "当前私聊没有可用的智能体。",
  "message.mentionedAgentsOffline": "{names} 当前离线。消息已持久排队，Teammate 会在运行时可用后尝试送达。",
  "message.agentPlaceholder": "消息 {name}",
  "message.channelPlaceholder": "消息 #{name}",
  "message.mentionSuggestions": "智能体建议",
  "message.agentSettings": "智能体设置",
  "agentSettings.settings": "设置",
  "agentSettings.workspace": "工作区",
  "agentSettings.close": "关闭",
  "agentSettings.loading": "正在加载…",
  "agentSettings.verifyingAccess": "正在验证访问权限…",
  "agentSettings.accessFailed": "无法打开智能体设置",
  "agentSettings.accessFailedDescription": "Teammate 无法确认你是否可以管理这个智能体。请检查连接后重试。",
  "agentSettings.basicInfo": "基本信息",
  "agentSettings.avatar": "头像",
  "agentSettings.customImage": "自定义图片",
  "agentSettings.chooseAvatar": "选择头像",
  "agentSettings.avatarUploadHint": "支持 PNG、JPEG 或 WebP，最大 2 MB",
  "agentSettings.avatarGeneratedHint": "选择一个生成头像",
  "agentSettings.upload": "上传",
  "agentSettings.defaultAvatar": "默认头像",
  "agentSettings.useDefaultAvatar": "使用默认头像",
  "agentSettings.generatedAvatar": "生成头像",
  "agentSettings.chooseGeneratedAvatar": "选择生成头像",
  "agentSettings.displayName": "显示名称",
  "agentSettings.description": "描述",
  "agentSettings.descriptionPlaceholder": "这个智能体负责什么？",
  "agentSettings.runtime": "运行时",
  "agentSettings.model": "模型",
  "agentSettings.selectModel": "选择模型",
  "agentSettings.connection": "模型连接",
  "agentSettings.chooseConnection": "请选择…",
  "agentSettings.loadingConnections": "正在加载模型连接…",
  "agentSettings.instructions": "指令",
  "agentSettings.systemPrompt": "系统提示词",
  "agentSettings.systemPromptPlaceholder": "这位队友是谁、负责什么…",
  "agentSettings.systemPromptHelp": "这里写的是这份说明书的开头。剩下的由 Teammate 补齐——怎么发消息、怎么用话题、怎么认领任务、怎么写文档、怎么记忆，以及什么时候该说话、什么时候不说。你只需要写清这位队友是谁、负责什么；上面这些不用重复，和它们冲突的写法通常也不会生效。",
  "agentSettings.promptPreview": "查看这个智能体收到的完整说明",
  "agentSettings.promptPreviewLoading": "生成中…",
  "agentSettings.promptPreviewMemory": "（运行时这里会插入你的 MEMORY.md）",
  "agentSettings.saved": "已保存！",
  "agentSettings.saveChanges": "保存更改",
  "agentSettings.skills": "技能",
  "agentSettings.installedSkills": "已安装 {count} 个",
  "agentSettings.loadingSkills": "正在加载技能…",
  "agentSettings.noSkills": "尚未安装技能",
  "agentSettings.skillsSourcePrefix": "技能从",
  "agentSettings.skillsSourceSuffix": "加载，并由所有智能体共享。",
  "agentSettings.dangerZone": "危险操作",
  "agentSettings.resetConversation": "重置会话",
  "agentSettings.deleteAgent": "移出工作区",
  "agentSettings.resetTitle": "重置会话？",
  "agentSettings.deleteTitle": "把这位队友移出工作区？",
  "agentSettings.resetDescription": "这会永久删除与该智能体私聊中的全部消息。",
  "agentSettings.deleteDescription": "TA 会停止接收消息并退出所有频道。TA 写过的东西——消息、文档、任务记录——都留在原处，并标记为已离职。",
  "agentSettings.cancel": "取消",
  "agentSettings.workspaceLoading": "正在加载工作区…",
  "agentSettings.runtimeOffline": "智能体运行时已离线",
  "agentSettings.runtimeOfflineDescription": "工作区文件位于运行该智能体的电脑上。请启动运行时后再在这里浏览。",
  "agentSettings.retry": "重试",
  "agentSettings.copyPath": "复制路径",
  "agentSettings.refresh": "刷新",
  "agentSettings.copied": "已复制！",
  "agentSettings.empty": "空",
  "agentSettings.workspaceEmpty": "工作区为空",
  "agentSettings.workspaceEmptyDescription": "智能体会在从会话中学习和工作时，将文件创建在这里。",
  "agentSettings.previewMarkdown": "预览 Markdown",
  "agentSettings.closePreview": "关闭预览",
  "agentSettings.workspaceInfoPrefix": "这是智能体的持久工作区，其中保存",
  "agentSettings.workspaceInfoSuffix": "以及帮助智能体在不同会话间保持上下文的笔记。",
  "agentSettings.error.unknown": "未知错误",
  "agentSettings.error.agentMissing": "未找到智能体设置。",
  "agentSettings.error.loadAgent": "无法加载智能体设置：{message}",
  "agentSettings.error.skillsInvalid": "技能服务返回了无效响应。",
  "agentSettings.error.requestStatus": "请求失败（{status}）",
  "agentSettings.error.loadSkills": "无法加载技能：{message}",
  "agentSettings.error.skillsOffline": "智能体运行时已离线，无法加载技能。",
  "agentSettings.error.loadConnections": "无法加载本地运行时与模型连接。",
  "agentSettings.error.avatarType": "请选择 PNG、JPEG 或 WebP 图片。",
  "agentSettings.error.avatarSize": "头像大小不能超过 2 MB。",
  "agentSettings.error.avatarRead": "无法读取这张图片。",
  "agentSettings.error.save": "无法保存更改：{message}",
  "agentSettings.error.reset": "无法重置会话：{message}",
  "agentSettings.error.delete": "无法删除智能体：{message}",
  "agentSettings.error.loadWorkspace": "无法加载工作区：{message}",
  "agentSettings.error.fileInvalid": "文件服务返回了无效响应。",
  "agentSettings.error.readFile": "无法读取文件：{message}",
  "agentSettings.error.readFileOffline": "智能体运行时已离线，无法读取文件。",
  "settings.title": "设置",
  "settings.description": "自定义这台电脑上的 Teammate。",
  "settings.loading": "正在加载设置…",
  "settings.loadFailed": "设置加载失败。",
  "settings.requestTimedOut": "请求超时，请重试。",
  "settings.profileLoading": "正在加载你的资料…",
  "settings.profileLoadFailed": "个人资料加载失败。",
  "settings.navGeneral": "通用",
  "settings.navProfile": "我的资料",
  "settings.navWorkspace": "工作区成员",
  "settings.navModels": "AI",
  "settings.engineHeading": "引擎",
  "settings.engineInUse": "使用中",
  "settings.engineVia": "通过",
  "settings.engineNeedsConnection": "在下方添加一个模型连接才能使用",
  "settings.engineReady": "可用",
  "settings.engineUnconfigured": "需要先配置连接",
  "settings.navChat": "聊天",
  "settings.navAdvanced": "高级",
  "settings.interface": "界面",
  "settings.profileDescription": "设置你在这台电脑上的会话中显示的资料。",
  "settings.profileAvatar": "头像",
  "settings.profileName": "显示名称",
  "settings.profileNameRequired": "显示名称不能为空。",
  "settings.profileSaveAfterSettingsError": "应用设置已保存，但个人资料未能保存。",
  "settings.profileUpload": "上传图片",
  "settings.profileAvatarHint": "支持 PNG、JPEG 或 WebP，最大 2 MB。",
  "settings.generalDescription": "设置应用的语言与外观。",
  "settings.language": "语言",
  "settings.languageZh": "简体中文",
  "settings.languageEn": "English",
  "settings.appearance": "外观",
  "settings.themeSystem": "跟随系统",
  "settings.themeLight": "浅色",
  "settings.themeDark": "深色",
  "settings.agentRuntime": "智能体运行时",
  "settings.runtimeDescription": "选择新智能体使用的本地引擎，并检查 CLI 是否可用。",
  "settings.availableRuntimes": "可用运行时",
  "settings.runtime": "默认运行引擎",
  "settings.runtimeClaude": "Claude Code",
  "settings.runtimeCodex": "Codex",
  "settings.runtimePi": "Pi / 自定义 API",
  "settings.defaultModel": "默认模型",
  "settings.thinkingLevel": "思考深度",
  "settings.thinkingLow": "低",
  "settings.thinkingMedium": "中等",
  "settings.thinkingHigh": "高",
  "settings.thinkingXHigh": "极高",
  "settings.thinkingHint": "作为新智能体的推理强度；不支持推理的模型会忽略此设置。",
  "settings.defaultSettings": "默认设置",
  "settings.workspaceOverride": "工作区设置",
  "settings.workspaceInherited": "继承默认模型和思考深度",
  "settings.capabilities": "模型能力",
  "settings.contextWindow": "上下文窗口",
  "settings.reasoningCapability": "推理",
  "settings.imageCapability": "图片输入",
  "settings.available": "可用",
  "settings.modelsDescription": "设置 Teammate 的默认思考方式，并管理它可以使用的模型连接。",
  "settings.modelOpus": "Opus — 能力最强",
  "settings.modelSonnet": "Sonnet — 均衡",
  "settings.modelHaiku": "Haiku — 最快",
  "settings.modelCodexDefault": "使用 Codex 默认模型",
  "settings.runtimeInstalled": "已安装",
  "settings.runtimeMissing": "未找到 CLI",
  "settings.codexModelPlaceholder": "default 或 Codex 模型 ID",
  "settings.modelHint": "新建智能体时使用。已有智能体继续保留各自的模型设置。",
  "settings.runtimeHint": "Claude Code 和 Codex 使用本机已安装的 CLI 与现有登录状态。",
  "settings.connections": "模型连接",
  "settings.connectionsHint": "Key 与 OAuth Token 只会加密保存在这台电脑，不会写入 SQLite。",
  "settings.chatGptOAuth": "ChatGPT Plus / Pro",
  "settings.chatGptOAuthHint": "通过浏览器安全登录，使用你的 Codex 订阅。",
  "settings.claudeOAuth": "Claude Pro / Max",
  "settings.claudeOAuthHint": "通过浏览器安全登录，使用你的 Claude 订阅。",
  "settings.copilotOAuth": "GitHub Copilot",
  "settings.copilotOAuthHint": "使用你的 Copilot 订阅，GitHub 会要求输入下方验证码。",
  "settings.deviceCodeHint": "在刚打开的页面里输入这个验证码：",
  "settings.connect": "连接",
  "settings.connecting": "等待登录…",
  "settings.connected": "已连接",
  "settings.addApi": "添加自定义 API",
  "settings.connectionName": "连接名称",
  "settings.provider": "API 协议",
  "settings.baseUrl": "Base URL",
  "settings.apiKey": "API Key",
  "settings.connectionModel": "模型 ID",
  "settings.addConnection": "保存连接",
  "settings.addConnectionTitle": "添加连接",
  "settings.addConnectionDescription": "连接 ChatGPT，或添加兼容 API。每个连接只展示自身可用的模型。",
  "settings.noConnections": "还没有模型连接。",
  "settings.defaultBadge": "默认",
  "settings.setDefault": "设为默认",
  "settings.connectionActions": "连接操作",
  "settings.localManagedConnection": "由本机已安装的 CLI 管理",
  "settings.connectionSaveFailed": "无法保存模型连接",
  "settings.connectionRefreshFailed": "连接已更新，但列表刷新失败。请重新打开设置后重试。",
  "settings.configurationCheck": "检查配置",
  "settings.configurationChecking": "正在检查…",
  "settings.configurationValid": "配置有效",
  "settings.configurationInvalid": "配置需要处理",
  "settings.refreshModels": "刷新模型",
  "settings.refreshingModels": "正在刷新…",
  "settings.modelsCount": "{count} 个可用模型",
  "settings.modelCatalogEmpty": "暂无可用模型",
  "settings.oauthFailed": "无法完成 ChatGPT 登录",
  "settings.removeConnection": "移除",
  "settings.removeConnectionTitle": "移除模型连接？",
  "settings.removeConnectionDescription": "这会移除以下连接的本地加密凭据：",
  "settings.removeConnectionFailed": "无法移除模型连接",
  "settings.removeConnectionRecoverable": "凭据已移除，但连接记录仍被保留。请重新连接或再次尝试移除。",
  "settings.removeDefaultConnectionBlocked": "请先选择另一个默认连接，再移除这个连接。",
  "settings.removeUsedConnectionBlocked": "请先为使用此连接的 {count} 个智能体重新选择连接。",
  "settings.chooseConnection": "模型连接",
  "settings.chat": "聊天",
  "settings.chatDescription": "控制智能体进度与失败信息在会话中的显示方式。",
  "settings.showActivityDetails": "显示活动详情",
  "settings.showActivityDetailsHint": "在可用时显示经过安全处理、面向用户的活动说明。",
  "settings.messageSounds": "消息提示音",
  "settings.messageSoundsHint": "发送或收到消息时播放轻量的本地提示音。",
  "settings.runtimeErrors": "运行时失败",
  "settings.runtimeErrorsHint": "失败会作为可见消息保存在会话中，不再静默丢失。",
  "settings.advanced": "高级",
  "settings.advancedDescription": "用于排查问题的本地服务与运行时诊断信息。",
  "settings.localService": "本地服务",
  "settings.executablePath": "可执行文件路径",
  "settings.embeddedRuntime": "内置运行时",
  "settings.cancel": "取消",
  "settings.save": "保存设置",
  "settings.saving": "保存中…",
  "createAgent.title": "新建智能体",
  "createAgent.description": "向工作区添加一个新的 AI 智能体。",
  "createAgent.name": "名称",
  "createAgent.namePlaceholder": "例如：设计助手、代码审查员…",
  "createAgent.descriptionField": "描述",
  "createAgent.descriptionPlaceholder": "这个智能体负责什么？",
  "createAgent.runtime": "运行引擎",
  "createAgent.model": "模型",
  "createAgent.instructions": "指令",
  "createAgent.instructionsPlaceholder": "告诉智能体应该如何工作、擅长什么、使用哪些工具…",
  "createAgent.optional": "可选",
  "createAgent.cancel": "取消",
  "createAgent.submit": "创建智能体",
  "createChannel.title": "新建频道",
  "createChannel.description": "为工作区创建一个多人协作频道。",
  "createChannel.name": "频道名称",
  "createChannel.namePlaceholder": "例如：设计、市场、开发…",
  "createChannel.descriptionField": "描述",
  "createChannel.descriptionPlaceholder": "这个频道用于讨论什么？",
  "createChannel.invite": "邀请智能体",
  "createChannel.optional": "可选",
  "createChannel.cancel": "取消",
  "createChannel.submit": "创建频道",
  "channel.manageAgents": "管理频道智能体",
  "channel.editTitle": "频道设置",
  "channel.editDescription": "更新频道信息，并选择可以参与的智能体。",
  "channel.agents": "频道中的智能体",
  "channel.save": "保存更改",
  "channel.notAuthenticated": "请重新登录后再管理频道。",
  "channel.notWorkspaceMember": "你已不再是当前工作区的成员。",
  "channel.loadingAgents": "正在加载可邀请的智能体…",
  "channel.searchAgents": "搜索智能体",
  "channel.noMatchingAgents": "没有匹配的智能体。",
  "channel.loadAgentsFailed": "无法加载可邀请的智能体。",
  "channel.loadTimedOut": "加载智能体超时，请重试。",
  "channel.createTimedOut": "创建频道超时，请刷新后再重试。",
  "channel.updateTimedOut": "保存频道超时，请刷新后再重试。",
  "channel.retry": "重试",
  "channel.noEligibleAgents": "当前工作区没有可邀请的智能体。",
  "channel.agentEligibilityChanged": "智能体的可用状态发生了变化，请确认更新后的选择再重试。",
  "channel.createFailed": "无法创建频道。",
  "channel.nameInUse": "当前工作区已经有同名频道。",
  "channel.inviteFailed": "无法邀请所选智能体。",
  "channel.createPartialFailure": "频道已经创建，但无法确认成员状态。它已显示在侧边栏，请先打开频道设置再重试。",
  "channel.membershipChangedElsewhere": "频道成员已在其他位置发生变化。你的选择仍被保留，请确认后再保存。",
  "channel.membershipSyncFailed": "无法同步频道成员。",
  "channel.notFound": "这个频道已不在当前工作区中。",
  "channel.updateNotApplied": "无法确认频道更新是否生效。",
  "channel.updateFailed": "无法更新频道。",
  "channel.delete": "删除频道",
  "channel.deleteTitle": "删除这个频道？",
  "channel.deleteDescription": "这会永久删除 #{name}、其中的任务和全部聊天记录。",
  "channel.deleteFailed": "无法删除频道。",
  "channel.deleteTimedOut": "删除频道超时，请刷新后再重试。",
  "channel.partialFailure": "部分更改可能已经保存，已重新加载最新成员状态。",
  "channel.rollbackSucceeded": "成员更改没有保存。",
};

export const defaultAppSettings: AppSettings = {
  language: "en-US",
  theme: "system",
  defaultRuntime: "codex",
  defaultModel: "default",
  defaultConnectionId: null,
  defaultThinkingLevel: "medium",
  showActivityDetails: true,
  messageSounds: true,
  documentEditor: "rich",
};

export function translate(
  language: AppLanguage,
  key: TranslationKey,
  values?: Record<string, string>,
) {
  let result = (language === "zh-CN" ? zh : en)[key];
  for (const [name, value] of Object.entries(values || {})) {
    result = result.replaceAll(`{${name}}`, value);
  }
  return result;
}

export interface AppSettingsContextValue {
  settings: AppSettings;
  t: (key: TranslationKey, values?: Record<string, string>) => string;
  openSettings?: () => void;
  updateSettings?: (settings: AppSettings) => void;
  settingsLoaded?: boolean;
  settingsLoadError?: string | null;
  reloadSettings?: () => void;
}

export const AppSettingsContext = createContext<AppSettingsContextValue>({
  settings: defaultAppSettings,
  t: (key, values) => translate(defaultAppSettings.language, key, values),
});

export function useAppSettings() {
  return useContext(AppSettingsContext);
}
